name: Testing

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing dependencies
        run: npm install

      - name: Testing
        run: npm test
